### ISSUE TITLE
Modeling by country

### ISSUE THREAD

**Issue by kamalhussain** [eladcn/coronavirus_prediction#4]
Thanks for sharing the code. Is there a way to project by country?

**Comment by eladcn** [comment]
Great question!
Although I didn't write any code to support this explicitly, the code is modular enough that it is possible to predict the stats for a specific country by altering the config.json file and adding another DataGrabber class, assuming you have the required data.

In order to do so, you will need to do the following:
1. Create a new DataGrabber class (you can name it however you want, for example: USADeathsDataGrabber), it doesn't have to inherit from class DataGrabber.
2. Implement the following method:
    `def get_dataset_file_name(self, dataset_date)`
    This method will return the dataset file name for a specific given date.
    For example, it may return:
    `"USA_" + dataset_date + ".csv".`
    You can find a good example for this in the CasesDataGrabber class.
3. (Optional) If you can fetch the data from the internet (instead of managing the dataset manually) and you would like to implement this feature, implement the following method:
    `def grab_data(self)`
    This method should fetch the data from a data source and store it into a file (which is the same format as mentioned in section 2).
4. Add the following configuration to the models array inside the config.json file:
`        {
            "model_name": "USA Deaths", // This is only used for display reasons.
            "polynomial_degree": 5, // A hyper parameter - The degree of the polynomial that we're trying to find.
            "datagrabber_class": "USADeathsDataGrabber", // The class we would like to use.
            "grab_data_from_server": true, // Set this to false if you would like to manage the dataset manually (i.e not use the grab_data(self) method).
            "offline_dataset_date": "2020-03-23", // If the dataset is managed manually - specify the date of the offline dataset file.
            "days_to_predict": 10 // How many days ahead you would like to predict.
        }`

Please note that the data should be formatted in a CSV file with the following structure:
```
0,value_for_day_0
1,value_for_day_1
2,value_for_day_2
.
.
.
```

Thanks to your question, I will add this tutorial to the readme file.
I hope I helped and please let me know if you need any further assistance.

**Comment by shlima** [comment]
:(
